targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: Upload
              custom_parser_import: 'coercers/coercers.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - package:http/http.dart
            - graphql_type: StringLowerCase
              dart_type: String
            - graphql_type: StringUpperCase
              dart_type: String
            - graphql_type: ImageUrl
              dart_type: String
            - graphql_type: GraphQlBigNumber
              custom_parser_import: 'coercers/coercers.dart'
              dart_type:
                name: Decimal
                imports:
                  - package:decimal/decimal.dart
            - graphql_type: UnixTimeSeconds
              custom_parser_import: 'coercers/coercers.dart'
              dart_type: int
            - graphql_type: UnixTimestamp
              custom_parser_import: 'coercers/coercers.dart'
              dart_type: int
            - graphql_type: ID
              dart_type: String
            - graphql_type: URL
              dart_type: String
            - graphql_type: JSONObject
              dart_type: String