default_platform(:android)

FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]
FIREBASE_TOKEN = ENV["FIREBASE_TOKEN"]

platform :android do
    desc "DEV - New Build to Firebase App Distribution"
    lane :android_dev do

        firebase_app_distribution(
           app: FIREBASE_APP_ID,
            firebase_cli_token: FIREBASE_TOKEN,
            apk_path: "../build/app/outputs/apk/dev/release/app-dev-release.apk",
            release_notes_file: "../android/release_notes_file.txt",
            groups: "mobile-team"
        )

    end
end

platform :android do
    desc "PROD - New Build to App Distribution Beta"
    lane :android_prod do

        firebase_app_distribution(
           app: FIREBASE_PROD_APP_ID,
            firebase_cli_token: FIREBASE_TOKEN,
            apk_path: "../build/app/outputs/apk/prod/release/app-prod-release.apk"
        )

    end
end
